[phases.setup]
nixPkgs = ['python39']

[phases.build]
cmds = ['python3 -m ensurepip --upgrade']

[phases.install]
cmds = ['pip3 install -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT'
